<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Contact Form Submission</title>
  <style>
    body {
      font-family: 'Poppins', sans-serif;
      background: linear-gradient(135deg, #f9f9f9, #eef2f3);
      margin: 0;
      padding: 40px;
      color: #333;
    }

    .container {
      max-width: 600px;
      background: #fff;
      margin: 0 auto;
      padding: 30px 40px;
      border-radius: 16px;
      box-shadow: 0 10px 25px rgba(0, 0, 0, 0.08);
      border-top: 6px solid #4A90E2;
    }

    h2 {
      text-align: center;
      color: #4A90E2;
      font-size: 26px;
      margin-bottom: 25px;
      letter-spacing: 0.5px;
    }

    p {
      font-size: 16px;
      line-height: 1.6;
      margin: 12px 0;
    }

    strong {
      color: #222;
      font-weight: 600;
    }

    .message-box {
      background: #f7faff;
      border-left: 4px solid #4A90E2;
      padding: 15px 20px;
      border-radius: 8px;
      font-style: italic;
      color: #444;
    }

    .footer {
      text-align: center;
      margin-top: 30px;
      font-size: 14px;
      color: #777;
      border-top: 1px solid #eee;
      padding-top: 15px;
    }

    /* Add a subtle hover card lift effect (for email previews that support it) */
    .container:hover {
      transform: translateY(-3px);
      transition: all 0.2s ease-in-out;
      box-shadow: 0 12px 28px rgba(0, 0, 0, 0.12);
    }
  </style>
</head>
<body>
  <div class="container">
    <h2>📩 New Contact Submission</h2>
    <p><strong>Name:</strong> {{ $data['name'] }}</p>
    <p><strong>Email:</strong> {{ $data['email'] }}</p>
    <p><strong>Mobile:</strong> {{ $data['mobile_no'] }}</p>
    <p><strong>Message:</strong></p>
    <div class="message-box">
      {{ $data['message'] }}
    </div>
    <div class="footer">
      This email was automatically generated by <a href="altiedge.com">AltiEdge</a>
    </div>
  </div>
</body>
</html>
